version: '3.9'

services:
  db:
    image: postgres:15
    container_name: leave-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    volumes:
      - leave-db-data:/var/lib/postgresql/data

volumes:
  leave-db-data:
