# Generated by Django 6.0 on 2026-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordDailyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE_ON_LEAVE_TODAY", "Employee: On Leave Today")
                        ],
                        max_length=64,
                    ),
                ),
                ("target_date", models.DateField()),
                ("channel_id", models.BigIntegerField()),
                ("message_id", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "target_date"), name="uniq_discord_daily_message"
                    )
                ],
            },
        ),
    ]
