# Generated by Django 6.0 on 2025-12-31 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_probation_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('VACATION', 'Vacation'), ('SICK', 'Sick')], max_length=20)),
                ('total', models.IntegerField()),
                ('used', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
