# Generated by Django 6.0 on 2026-01-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_app", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("VACATION", "Vacation"),
                            ("SICK", "Sick"),
                            ("MATERNITY", "Maternity"),
                            ("PATERNITY", "Paternity"),
                            ("BEREAVEMENT", "Bereavement"),
                            ("WFH", "Work From Home"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Day"),
                            ("AM", "Morning"),
                            ("PM", "Afternoon"),
                        ],
                        default="FULL",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="user_app.employee",
                    ),
                ),
            ],
        ),
    ]
