# Generated by Django 6.0 on 2026-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0002_leaverequest_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="discord_message_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
