# Generated by Django 6.0 on 2026-01-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0003_leaverequest_discord_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="reapplied_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reapplications",
                to="form_app.leaverequest",
            ),
        ),
    ]
