# Generated by Django 6.0 on 2026-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0004_leaverequest_reapplied_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("VOIDED", "Voided"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
