# Generated by Django 6.0 on 2026-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0005_alter_leaverequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="has_reapplied",
            field=models.BooleanField(default=False),
        ),
    ]
