# Generated by Django 6.0 on 2026-02-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0006_leaverequest_has_reapplied"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="end_session",
            field=models.CharField(
                choices=[("FULL", "Full Day"), ("AM", "Morning"), ("PM", "Afternoon")],
                default="FULL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="start_session",
            field=models.CharField(
                choices=[("FULL", "Full Day"), ("AM", "Morning"), ("PM", "Afternoon")],
                default="FULL",
                max_length=10,
            ),
        ),
    ]
