# Generated by Django 6.0 on 2026-02-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0007_leaverequest_end_session_leaverequest_start_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
