# Generated by Django 6.0 on 2026-02-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0008_leaverequest_approved_at_leaverequest_notified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="notified_at",
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="notified_admin_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="notified_employee_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
