# Generated by Django 6.0 on 2026-02-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0012_leaverequest_approval_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="google_event_id",
            field=models.CharField(blank=True, default=""),
        ),
    ]
