# Generated by Django 6.0 on 2026-02-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0013_alter_leaverequest_google_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="google_event_id",
            field=models.TextField(blank=True, default=""),
        ),
    ]
