# Generated by Django 6.0 on 2026-03-11 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0015_holiday"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequestDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Day"),
                            ("AM", "Morning"),
                            ("PM", "Afternoon"),
                        ],
                        default="FULL",
                        max_length=10,
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="form_app.leaverequest",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("leave_request", "date"), name="uniq_leave_request_day"
                    )
                ],
            },
        ),
    ]
