# Generated by Django 6.0 on 2026-02-16 12:16

from django.db import migrations


def _ensure_indexes_forward(apps, schema_editor):
    """Postgres-safe: rename old index if present; ensure expected index exists."""
    if schema_editor.connection.vendor != "postgresql":
        return

    Model = apps.get_model("auth_app", "PasswordResetToken")
    table = Model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT indexname
            FROM pg_indexes
            WHERE schemaname = current_schema() AND tablename = %s
            """,
            [table],
        )
        existing = {row[0] for row in cursor.fetchall()}

    def rename_if_exists(old: str, new: str) -> None:
        if old in existing and new not in existing:
            schema_editor.execute(
                f"ALTER INDEX {schema_editor.quote_name(old)} RENAME TO {schema_editor.quote_name(new)};"
            )
            existing.discard(old)
            existing.add(new)

    rename_if_exists(
        "auth_app_pa_expires__a1feaf_idx", "auth_app_pa_expires_0d700d_idx"
    )
    rename_if_exists("auth_app_pa_used_at_0da7b1_idx", "auth_app_pa_used_at_a18f43_idx")


def _ensure_indexes_backward(apps, schema_editor):
    """Best-effort reverse: rename back if possible (does not drop indexes)."""
    if schema_editor.connection.vendor != "postgresql":
        return

    Model = apps.get_model("auth_app", "PasswordResetToken")
    table = Model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT indexname
            FROM pg_indexes
            WHERE schemaname = current_schema() AND tablename = %s
            """,
            [table],
        )
        existing = {row[0] for row in cursor.fetchall()}

    def rename_if_exists(old: str, new: str) -> None:
        if old in existing and new not in existing:
            schema_editor.execute(
                f"ALTER INDEX {schema_editor.quote_name(old)} RENAME TO {schema_editor.quote_name(new)};"
            )
            existing.discard(old)
            existing.add(new)

    rename_if_exists(
        "auth_app_pa_expires_0d700d_idx", "auth_app_pa_expires__a1feaf_idx"
    )
    rename_if_exists("auth_app_pa_used_at_a18f43_idx", "auth_app_pa_used_at_0da7b1_idx")


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _ensure_indexes_forward,
                    reverse_code=_ensure_indexes_backward,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="passwordresettoken",
                    new_name="auth_app_pa_expires_0d700d_idx",
                    old_name="auth_app_pa_expires__a1feaf_idx",
                ),
                migrations.RenameIndex(
                    model_name="passwordresettoken",
                    new_name="auth_app_pa_used_at_a18f43_idx",
                    old_name="auth_app_pa_used_at_0da7b1_idx",
                ),
            ],
        ),
    ]
