# Generated by Django 6.0 on 2026-01-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
