# Generated by Django 6.0 on 2026-01-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_employee_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="user_app.employee",
            ),
        ),
    ]
