# Generated by Django 6.0 on 2026-01-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_alter_profile_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="current_project",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
