# Generated by Django 6.0 on 2026-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_employee_current_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="reset_leave_balance",
            field=models.BooleanField(default=False),
        ),
    ]
