# Generated by Django 6.0 on 2026-02-23 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0009_employee_leave_limits_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="leave_limits_override",
        ),
    ]
