name: Deploy to leave-management Azure VM 

on:
  push:
    branches:
      - "main"

jobs:
  call-reusable-workflow:
    uses: Avinto-IT/AvintoActionsPipeline/.github/workflows/reusable-workflow.yml@master
    with:
      docker_file: "docker-compose.yml" # Root of the repo
      deployment-path: "/home/azureuser/Avinto/Avinto-leave-management/leave-management-system-backend" # Project path o VM
      branch-name: ${{github.ref_name}}
    secrets:
      vm_ip: ${{ secrets.LEAVE_MANAGEMENT_VM_IP }} 
      ssh_key: ${{ secrets.LEAVE_MANAGEMENT_SSH_PRIVATE_KEY }} 
      user_name: ${{ secrets.LEAVE_MANAGEMENT_VM_USER_NAME }}

      